export const SUBREDDIT_ARTICLES_FETCH_REQUEST = 'SUBREDDIT_ARTICLES_FETCH_REQUEST';
export const SUBREDDIT_ARTICLES_FETCH_RESPONSE = 'SUBREDDIT_ARTICLES_FETCH_RESPONSE';
export const SUBREDDIT_ARTICLES_FETCH_ERROR = 'SUBREDDIT_ARTICLES_FETCH_ERROR';