export const SUBREDDIT_ARTICLES_FETCH_REQUEST = 'SUBREDDIT_ARTICLES_FETCH_REQUEST';
export const SUBREDDIT_ARTICLES_FETCH_RESPONSE = 'SUBREDDIT_ARTICLES_FETCH_RESPONSE';
export const SUBREDDIT_ARTICLES_FETCH_ERROR = 'SUBREDDIT_ARTICLES_FETCH_ERROR';
export const SUBREDDIT_DETAILS_FETCH_REQUEST = 'SUBREDDIT_DETAILS_FETCH_REQUEST';
export const SUBREDDIT_DETAILS_FETCH_RESPONSE = 'SUBREDDIT_DETAILS_FETCH_RESPONSE';
export const SUBREDDIT_DETAILS_FETCH_ERROR = 'SUBREDDIT_DETAILS_FETCH_ERROR';
export const SUBREDDIT_EDITOR_CHANGE = 'SUBREDDIT_EDITOR_CHANGE';